/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as HelpTopicRouteImport } from './routes/help.$topic'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as ApiProductsIdRouteImport } from './routes/api/products.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const HelpTopicRoute = HelpTopicRouteImport.update({
  id: '/help/$topic',
  path: '/help/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/help/$topic': typeof HelpTopicRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/help/$topic': typeof HelpTopicRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRouteWithChildren
  '/search': typeof SearchRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/help/$topic': typeof HelpTopicRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/checkout'
    | '/products'
    | '/search'
    | '/admin/produtos'
    | '/api/products'
    | '/help/$topic'
    | '/products/$slug'
    | '/sitemap/xml'
    | '/api/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/checkout'
    | '/products'
    | '/search'
    | '/admin/produtos'
    | '/api/products'
    | '/help/$topic'
    | '/products/$slug'
    | '/sitemap/xml'
    | '/api/products/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/checkout'
    | '/products'
    | '/search'
    | '/admin/produtos'
    | '/api/products'
    | '/help/$topic'
    | '/products/$slug'
    | '/sitemap/xml'
    | '/api/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CheckoutRoute: typeof CheckoutRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  SearchRoute: typeof SearchRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  HelpTopicRoute: typeof HelpTopicRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/help/$topic': {
      id: '/help/$topic'
      path: '/help/$topic'
      fullPath: '/help/$topic'
      preLoaderRoute: typeof HelpTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof ApiProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ApiProductsRouteChildren {
  ApiProductsIdRoute: typeof ApiProductsIdRoute
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsIdRoute: ApiProductsIdRoute,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CheckoutRoute: CheckoutRoute,
  ProductsRoute: ProductsRouteWithChildren,
  SearchRoute: SearchRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  HelpTopicRoute: HelpTopicRoute,
  SitemapXmlRoute: SitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
